/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ConCliente;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelos.Juego;

/**
 *
 * @author Angel
 */
public class JFCliente extends javax.swing.JFrame {
     private ConCliente cc;
    private boolean haContestado = false;
    private boolean haFinalizado = false;
    private Juego juego;
    private int puerto = 6010;
    private String ipCliente = "192.168.0.18";
    private String nombre = "Angel";
    /**
     * Creates new form JFCliente
     */
    public JFCliente() {
        initComponents();
        cc = new ConCliente(nombre, puerto, ipCliente);
        juego = new Juego();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preguntaServidor = new javax.swing.JLabel();
        puntosCliente = new javax.swing.JLabel();
        opcion1Cliente = new javax.swing.JButton();
        opcion2Cliente = new javax.swing.JButton();
        opcion3Cliente = new javax.swing.JButton();
        opcion4Cliente = new javax.swing.JButton();
        btUnirseAPartidaCliente = new javax.swing.JButton();
        Cpuntos = new javax.swing.JLabel();
        preguntaServidor1 = new javax.swing.JLabel();

        preguntaServidor.setText("Pregunta");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        puntosCliente.setText("0");

        opcion1Cliente.setText("jButton1");

        opcion2Cliente.setText("jButton2");

        opcion3Cliente.setText("jButton3");

        opcion4Cliente.setText("jButton4");

        btUnirseAPartidaCliente.setText("Unirse a una partida");
        btUnirseAPartidaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnirseAPartidaClienteActionPerformed(evt);
            }
        });

        Cpuntos.setText("Puntos:");

        preguntaServidor1.setText("Pregunta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Cpuntos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntosCliente)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opcion1Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(opcion2Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opcion3Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opcion4Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preguntaServidor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btUnirseAPartidaCliente)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btUnirseAPartidaCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cpuntos)
                                    .addComponent(puntosCliente))))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(preguntaServidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(opcion1Cliente)
                .addGap(35, 35, 35)
                .addComponent(opcion2Cliente)
                .addGap(43, 43, 43)
                .addComponent(opcion3Cliente)
                .addGap(32, 32, 32)
                .addComponent(opcion4Cliente)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUnirseAPartidaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnirseAPartidaClienteActionPerformed
            
    }//GEN-LAST:event_btUnirseAPartidaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cpuntos;
    private javax.swing.JButton btUnirseAPartidaCliente;
    private javax.swing.JButton opcion1Cliente;
    private javax.swing.JButton opcion2Cliente;
    private javax.swing.JButton opcion3Cliente;
    private javax.swing.JButton opcion4Cliente;
    private javax.swing.JLabel preguntaServidor;
    private javax.swing.JLabel preguntaServidor1;
    private javax.swing.JLabel puntosCliente;
    // End of variables declaration//GEN-END:variables
}
